In [1]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("archive (1)/PJME_hourly.csv",parse_dates=[0])
df.head()

             Datetime  PJME_MW
0 2002-12-31 01:00:00  26498.0
1 2002-12-31 02:00:00  25147.0
2 2002-12-31 03:00:00  24574.0
3 2002-12-31 04:00:00  24393.0
4 2002-12-31 05:00:00  24860.0

In [3]:
print(df.dtypes)
df.info()

Datetime    datetime64[us]
PJME_MW            float64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 145366 entries, 0 to 145365
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  145366 non-null  datetime64[us]
 1   PJME_MW   145366 non-null  float64
dtypes: datetime64[us](1), float64(1)
memory usage: 2.2 MB

In [4]:
df = df.set_index("Datetime")

In [5]:
df.head()

                     PJME_MW
Datetime
2002-12-31 01:00:00  26498.0
2002-12-31 02:00:00  25147.0
2002-12-31 03:00:00  24574.0
2002-12-31 04:00:00  24393.0
2002-12-31 05:00:00  24860.0

In [6]:
df.index.dtype

dtype('<M8[us]')

In [7]:
df.index.nunique()

145362

In [8]:
df.index

DatetimeIndex(['2002-12-31 01:00:00', '2002-12-31 02:00:00',
               '2002-12-31 03:00:00', '2002-12-31 04:00:00',
               '2002-12-31 05:00:00', '2002-12-31 06:00:00',
               '2002-12-31 07:00:00', '2002-12-31 08:00:00',
               '2002-12-31 09:00:00', '2002-12-31 10:00:00',
               ...
               '2018-01-01 15:00:00', '2018-01-01 16:00:00',
               '2018-01-01 17:00:00', '2018-01-01 18:00:00',
               '2018-01-01 19:00:00', '2018-01-01 20:00:00',
               '2018-01-01 21:00:00', '2018-01-01 22:00:00',
               '2018-01-01 23:00:00', '2018-01-02 00:00:00'],
              dtype='datetime64[us]', name='Datetime', length=145366, freq=None)

In [9]:
pd.date_range(start = "2002-12-31 01:00:00", end = "2018-01-02 00:00:00", freq="h")

DatetimeIndex(['2002-12-31 01:00:00', '2002-12-31 02:00:00',
               '2002-12-31 03:00:00', '2002-12-31 04:00:00',
               '2002-12-31 05:00:00', '2002-12-31 06:00:00',
               '2002-12-31 07:00:00', '2002-12-31 08:00:00',
               '2002-12-31 09:00:00', '2002-12-31 10:00:00',
               ...
               '2018-01-01 15:00:00', '2018-01-01 16:00:00',
               '2018-01-01 17:00:00', '2018-01-01 18:00:00',
               '2018-01-01 19:00:00', '2018-01-01 20:00:00',
               '2018-01-01 21:00:00', '2018-01-01 22:00:00',
               '2018-01-01 23:00:00', '2018-01-02 00:00:00'],
              dtype='datetime64[us]', length=131544, freq='h')

In [10]:
df.index.is_monotonic_increasing

False

In [11]:
df.index.duplicated().sum()

np.int64(4)

In [12]:
df.index.to_series().diff().value_counts()

Datetime
0 days 01:00:00      139275
-2 days +01:00:00      6040
0 days 02:00:00          29
729 days 01:00:00         8
728 days 01:00:00         7
0 days 00:00:00           4
-2 days +02:00:00         1
577 days 01:00:00         1
Name: count, dtype: int64

In [13]:
df.index.min()

Timestamp('2002-01-01 01:00:00')

In [14]:
df.index.max()

Timestamp('2018-08-03 00:00:00')

In [15]:
df.index.nunique()

145362

In [16]:
df.sort_index()

                     PJME_MW
Datetime
2002-01-01 01:00:00  30393.0
2002-01-01 02:00:00  29265.0
2002-01-01 03:00:00  28357.0
2002-01-01 04:00:00  27899.0
2002-01-01 05:00:00  28057.0
...                      ...
2018-08-02 20:00:00  44057.0
2018-08-02 21:00:00  43256.0
2018-08-02 22:00:00  41552.0
2018-08-02 23:00:00  38500.0
2018-08-03 00:00:00  35486.0

[145366 rows x 1 columns]

In [22]:
duplikaty = df.index.duplicated(keep=False)
duplikaty1 = df.index.duplicated(keep='first')
duplikatylast = df.index.duplicated(keep='last')

In [ ]:
duplikaty.sum()

np.int64(4)

In [ ]:
len(duplikaty)

145366

In [28]:
duplikatylast

array([False, False, False, ..., False, False, False], shape=(145366,))

In [30]:
df.loc[duplikaty].sort_index()

                     PJME_MW
Datetime
2014-11-02 02:00:00  22935.0
2014-11-02 02:00:00  23755.0
2015-11-01 02:00:00  21567.0
2015-11-01 02:00:00  21171.0
2016-11-06 02:00:00  20795.0
2016-11-06 02:00:00  21692.0
2017-11-05 02:00:00  21236.0
2017-11-05 02:00:00  20666.0

In [31]:
zmianaczasu = df.index.to_series().diff()

In [32]:
zmianaczasu

Datetime
2002-12-31 01:00:00               NaT
2002-12-31 02:00:00   0 days 01:00:00
2002-12-31 03:00:00   0 days 01:00:00
2002-12-31 04:00:00   0 days 01:00:00
2002-12-31 05:00:00   0 days 01:00:00
                            ...
2018-01-01 20:00:00   0 days 01:00:00
2018-01-01 21:00:00   0 days 01:00:00
2018-01-01 22:00:00   0 days 01:00:00
2018-01-01 23:00:00   0 days 01:00:00
2018-01-02 00:00:00   0 days 01:00:00
Name: Datetime, Length: 145366, dtype: timedelta64[us]